const AuthActions = {
  AUTH_ME: 'AUTH_ME',
  AUTH_ME_SUCCESS: 'AUTH_ME_SUCCESS',
  AUTH_ME_FAILURE: 'AUTH_ME_FAILURE',

  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  SIGN_OUT: 'SIGN_OUT',
};
export default AuthActions;
