const CategoryActions = {
  GET_GRAPH_CATEGORY: 'GET_GRAPH_CATEGORY',
  GET_GRAPH_CATEGORY_SUCCESS: 'GET_LIST_ROOT_CATEGORY_SUCCESS',
  GET_GRAPH_CATEGORY_FAILURE: 'GET_LIST_ROOT_CATEGORY_FAILURE',
};
export default CategoryActions;
